# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\sours\UI\about_app.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AboutApp(object):
    def setupUi(self, AboutApp):
        AboutApp.setObjectName("AboutApp")
        AboutApp.resize(500, 350)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AboutApp.sizePolicy().hasHeightForWidth())
        AboutApp.setSizePolicy(sizePolicy)
        AboutApp.setMinimumSize(QtCore.QSize(500, 350))
        AboutApp.setMaximumSize(QtCore.QSize(500, 350))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ico/icons/conver_ico_0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AboutApp.setWindowIcon(icon)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(AboutApp)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(AboutApp)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 463, 454))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_about = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.lbl_about.setFont(font)
        self.lbl_about.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_about.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lbl_about.setWordWrap(True)
        self.lbl_about.setObjectName("lbl_about")
        self.verticalLayout.addWidget(self.lbl_about, 0, QtCore.Qt.AlignTop)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.btn_box = QtWidgets.QDialogButtonBox(AboutApp)
        self.btn_box.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.btn_box.setCenterButtons(True)
        self.btn_box.setObjectName("btn_box")
        self.verticalLayout_2.addWidget(self.btn_box)

        self.retranslateUi(AboutApp)
        self.btn_box.rejected.connect(AboutApp.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AboutApp)

    def retranslateUi(self, AboutApp):
        _translate = QtCore.QCoreApplication.translate
        AboutApp.setWindowTitle(_translate("AboutApp", "О программе."))
        self.lbl_about.setText(_translate("AboutApp", "<html><head/><body><p align=\"center\">Программа &quot;<span style=\" font-weight:600;\">Конвертер показаний</span>&quot;. </p><p>Программа позволяет преобразовывать показания допрошенных по уголовному делу лиц, от первого лица в текст от третьего лица. </p><p>Имеет функции минималистичного редактора текста, автоматически исправляет текст в зависимости от выбранных настроек и приводит текст в одинаковый вид для вставки в обвинительное заключение. Встроен редактор словаря, используемого для автоматической замены. По сравнению со старыми версиями конвертера в словаре используется массив, состоящий из слов в единственном и множественном числе, в первом и от третьего лица, неопределенной формы. </p><p>Для конвертирования текста показаний: </p><p>1. Вставьте показания из опроса в текстовое поле (при необходимости отредактируйте). </p><p>2. Выберете, чьи показания (женщины или мужчины) преобразуются. </p><p>Поздравляю, текст преобразован. Осталось его скопировать и вставить, куда необходимо. (если включена настройка, то текст сразу скопируется в буфер обмена при преобразовании) </p><p>Предложения по улучшению или дополнению функционала присылайте на почту andmoni@yandex.ru </p><p align=\"right\">С уважением, Андрей. </p></body></html>"))
import res_rc
