# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\sours\UI\d_converter_edit_words.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogConverterEditWords(object):
    def setupUi(self, DialogConverterEditWords):
        DialogConverterEditWords.setObjectName("DialogConverterEditWords")
        DialogConverterEditWords.resize(500, 200)
        DialogConverterEditWords.setMinimumSize(QtCore.QSize(500, 200))
        DialogConverterEditWords.setMaximumSize(QtCore.QSize(500, 200))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ico/icons/edit_doc.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DialogConverterEditWords.setWindowIcon(icon)
        self.verticalLayout_main = QtWidgets.QVBoxLayout(DialogConverterEditWords)
        self.verticalLayout_main.setObjectName("verticalLayout_main")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setContentsMargins(6, -1, -1, 6)
        self.formLayout.setObjectName("formLayout")
        self.lb_indefinite = QtWidgets.QLabel(DialogConverterEditWords)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lb_indefinite.setFont(font)
        self.lb_indefinite.setObjectName("lb_indefinite")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lb_indefinite)
        self.le_indefinite = QtWidgets.QLineEdit(DialogConverterEditWords)
        self.le_indefinite.setObjectName("le_indefinite")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.le_indefinite)
        self.lb_f_person = QtWidgets.QLabel(DialogConverterEditWords)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lb_f_person.setFont(font)
        self.lb_f_person.setObjectName("lb_f_person")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lb_f_person)
        self.le_f_person = QtWidgets.QLineEdit(DialogConverterEditWords)
        self.le_f_person.setObjectName("le_f_person")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.le_f_person)
        self.lb_t_person = QtWidgets.QLabel(DialogConverterEditWords)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lb_t_person.setFont(font)
        self.lb_t_person.setObjectName("lb_t_person")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lb_t_person)
        self.le_t_person = QtWidgets.QLineEdit(DialogConverterEditWords)
        self.le_t_person.setObjectName("le_t_person")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.le_t_person)
        self.lb_f_persons = QtWidgets.QLabel(DialogConverterEditWords)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lb_f_persons.setFont(font)
        self.lb_f_persons.setObjectName("lb_f_persons")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lb_f_persons)
        self.le_f_persons = QtWidgets.QLineEdit(DialogConverterEditWords)
        self.le_f_persons.setObjectName("le_f_persons")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.le_f_persons)
        self.lb_t_persons = QtWidgets.QLabel(DialogConverterEditWords)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lb_t_persons.setFont(font)
        self.lb_t_persons.setObjectName("lb_t_persons")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lb_t_persons)
        self.le_t_persons = QtWidgets.QLineEdit(DialogConverterEditWords)
        self.le_t_persons.setObjectName("le_t_persons")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.le_t_persons)
        self.verticalLayout_main.addLayout(self.formLayout)
        self.dbn_box = QtWidgets.QDialogButtonBox(DialogConverterEditWords)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dbn_box.sizePolicy().hasHeightForWidth())
        self.dbn_box.setSizePolicy(sizePolicy)
        self.dbn_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.dbn_box.setObjectName("dbn_box")
        self.verticalLayout_main.addWidget(self.dbn_box)

        self.retranslateUi(DialogConverterEditWords)
        self.dbn_box.accepted.connect(DialogConverterEditWords.saveWords) # type: ignore
        self.dbn_box.rejected.connect(DialogConverterEditWords.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DialogConverterEditWords)

    def retranslateUi(self, DialogConverterEditWords):
        _translate = QtCore.QCoreApplication.translate
        DialogConverterEditWords.setWindowTitle(_translate("DialogConverterEditWords", "Редактор слов конвертера"))
        DialogConverterEditWords.setToolTip(_translate("DialogConverterEditWords", "Позволяет отредактировать слово и его спряжения для словаря замены."))
        self.lb_indefinite.setToolTip(_translate("DialogConverterEditWords", "Неопределенная форма слова"))
        self.lb_indefinite.setText(_translate("DialogConverterEditWords", "Неопределенная форма:"))
        self.le_indefinite.setToolTip(_translate("DialogConverterEditWords", "Неопределенная форма слова"))
        self.lb_f_person.setToolTip(_translate("DialogConverterEditWords", "Слово спряженное в первом лице (единственном числе)"))
        self.lb_f_person.setText(_translate("DialogConverterEditWords", "В первом лице (единственном числе):"))
        self.le_f_person.setToolTip(_translate("DialogConverterEditWords", "Слово спряженное в первом лице (единственном числе)"))
        self.lb_t_person.setToolTip(_translate("DialogConverterEditWords", "Слово спряженное в третьем лице (единственном числе)"))
        self.lb_t_person.setText(_translate("DialogConverterEditWords", "В третьем лице (единственном числе):"))
        self.le_t_person.setToolTip(_translate("DialogConverterEditWords", "Слово спряженное в третьем лице (единственном числе)"))
        self.lb_f_persons.setToolTip(_translate("DialogConverterEditWords", "Слово спряженное в первом лице (множественном числе)"))
        self.lb_f_persons.setText(_translate("DialogConverterEditWords", "В первом лице (множественном числе):"))
        self.le_f_persons.setToolTip(_translate("DialogConverterEditWords", "Слово спряженное в первом лице (множественном числе)"))
        self.lb_t_persons.setToolTip(_translate("DialogConverterEditWords", "Слово спряженное в третьем лице (множественном числе)"))
        self.lb_t_persons.setText(_translate("DialogConverterEditWords", "В третьем лице (множественном числе):"))
        self.le_t_persons.setToolTip(_translate("DialogConverterEditWords", "Слово спряженное в третьем лице (множественном числе)"))
import res_rc
