# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\sours\UI\d_converter_dictionary.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogConverterEditDictionary(object):
    def setupUi(self, DialogConverterEditDictionary):
        DialogConverterEditDictionary.setObjectName("DialogConverterEditDictionary")
        DialogConverterEditDictionary.resize(924, 654)
        DialogConverterEditDictionary.setMinimumSize(QtCore.QSize(770, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ico/icons/conver_ico_0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DialogConverterEditDictionary.setWindowIcon(icon)
        self.verticalLayout_main = QtWidgets.QVBoxLayout(DialogConverterEditDictionary)
        self.verticalLayout_main.setContentsMargins(-1, -1, -1, 20)
        self.verticalLayout_main.setObjectName("verticalLayout_main")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tbtn_new = QtWidgets.QToolButton(DialogConverterEditDictionary)
        self.tbtn_new.setMinimumSize(QtCore.QSize(40, 40))
        self.tbtn_new.setMaximumSize(QtCore.QSize(40, 40))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/ico/icons/new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbtn_new.setIcon(icon1)
        self.tbtn_new.setIconSize(QtCore.QSize(32, 32))
        self.tbtn_new.setObjectName("tbtn_new")
        self.horizontalLayout.addWidget(self.tbtn_new)
        self.tbtn_edit = QtWidgets.QToolButton(DialogConverterEditDictionary)
        self.tbtn_edit.setEnabled(False)
        self.tbtn_edit.setMinimumSize(QtCore.QSize(40, 40))
        self.tbtn_edit.setMaximumSize(QtCore.QSize(40, 40))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/ico/icons/edit_doc.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbtn_edit.setIcon(icon2)
        self.tbtn_edit.setIconSize(QtCore.QSize(32, 32))
        self.tbtn_edit.setObjectName("tbtn_edit")
        self.horizontalLayout.addWidget(self.tbtn_edit)
        self.tbtn_delete = QtWidgets.QToolButton(DialogConverterEditDictionary)
        self.tbtn_delete.setEnabled(False)
        self.tbtn_delete.setMinimumSize(QtCore.QSize(40, 40))
        self.tbtn_delete.setMaximumSize(QtCore.QSize(40, 40))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/ico/icons/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbtn_delete.setIcon(icon3)
        self.tbtn_delete.setIconSize(QtCore.QSize(32, 32))
        self.tbtn_delete.setObjectName("tbtn_delete")
        self.horizontalLayout.addWidget(self.tbtn_delete)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.le_filter = QtWidgets.QLineEdit(DialogConverterEditDictionary)
        self.le_filter.setMinimumSize(QtCore.QSize(0, 32))
        self.le_filter.setMaximumSize(QtCore.QSize(16777215, 32))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.le_filter.setFont(font)
        self.le_filter.setObjectName("le_filter")
        self.horizontalLayout_2.addWidget(self.le_filter)
        self.tbtn_clear_filter = QtWidgets.QToolButton(DialogConverterEditDictionary)
        self.tbtn_clear_filter.setEnabled(False)
        self.tbtn_clear_filter.setMinimumSize(QtCore.QSize(48, 32))
        self.tbtn_clear_filter.setMaximumSize(QtCore.QSize(48, 32))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.tbtn_clear_filter.setFont(font)
        self.tbtn_clear_filter.setIconSize(QtCore.QSize(24, 24))
        self.tbtn_clear_filter.setObjectName("tbtn_clear_filter")
        self.horizontalLayout_2.addWidget(self.tbtn_clear_filter)
        self.horizontalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_main.addLayout(self.horizontalLayout)
        self.tw_replacement_dictionary = QtWidgets.QTableWidget(DialogConverterEditDictionary)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tw_replacement_dictionary.setFont(font)
        self.tw_replacement_dictionary.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tw_replacement_dictionary.setProperty("showDropIndicator", False)
        self.tw_replacement_dictionary.setDragDropOverwriteMode(False)
        self.tw_replacement_dictionary.setAlternatingRowColors(True)
        self.tw_replacement_dictionary.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tw_replacement_dictionary.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tw_replacement_dictionary.setRowCount(5)
        self.tw_replacement_dictionary.setObjectName("tw_replacement_dictionary")
        self.tw_replacement_dictionary.setColumnCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tw_replacement_dictionary.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_replacement_dictionary.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_replacement_dictionary.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_replacement_dictionary.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_replacement_dictionary.setHorizontalHeaderItem(4, item)
        self.tw_replacement_dictionary.horizontalHeader().setDefaultSectionSize(170)
        self.tw_replacement_dictionary.horizontalHeader().setSortIndicatorShown(True)
        self.tw_replacement_dictionary.horizontalHeader().setStretchLastSection(True)
        self.tw_replacement_dictionary.verticalHeader().setVisible(False)
        self.verticalLayout_main.addWidget(self.tw_replacement_dictionary)
        self.l_sum_info = QtWidgets.QLabel(DialogConverterEditDictionary)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.l_sum_info.setFont(font)
        self.l_sum_info.setObjectName("l_sum_info")
        self.verticalLayout_main.addWidget(self.l_sum_info)
        self.dbn_box = QtWidgets.QDialogButtonBox(DialogConverterEditDictionary)
        self.dbn_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.dbn_box.setObjectName("dbn_box")
        self.verticalLayout_main.addWidget(self.dbn_box)

        self.retranslateUi(DialogConverterEditDictionary)
        self.dbn_box.rejected.connect(DialogConverterEditDictionary.reject) # type: ignore
        self.tbtn_new.clicked.connect(DialogConverterEditDictionary.addWords) # type: ignore
        self.tbtn_edit.clicked.connect(DialogConverterEditDictionary.editWords) # type: ignore
        self.tbtn_delete.clicked.connect(DialogConverterEditDictionary.deleteWords) # type: ignore
        self.tw_replacement_dictionary.doubleClicked['QModelIndex'].connect(DialogConverterEditDictionary.editWords) # type: ignore
        self.tbtn_clear_filter.clicked.connect(self.le_filter.clear) # type: ignore
        self.le_filter.textChanged['QString'].connect(DialogConverterEditDictionary.filterWords) # type: ignore
        self.dbn_box.accepted.connect(DialogConverterEditDictionary.saveWordsDictionary) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DialogConverterEditDictionary)

    def retranslateUi(self, DialogConverterEditDictionary):
        _translate = QtCore.QCoreApplication.translate
        DialogConverterEditDictionary.setWindowTitle(_translate("DialogConverterEditDictionary", "Изменение словаря конвертера."))
        DialogConverterEditDictionary.setToolTip(_translate("DialogConverterEditDictionary", "Окно позволяет изменить словарь для замены слов используемый программой для приобразования показаний."))
        self.tbtn_new.setToolTip(_translate("DialogConverterEditDictionary", "Добавить в словарь для конвертирования\n"
"новое слово и его спряжения."))
        self.tbtn_new.setText(_translate("DialogConverterEditDictionary", "Новое\n"
"слово"))
        self.tbtn_new.setShortcut(_translate("DialogConverterEditDictionary", "Ctrl+N"))
        self.tbtn_edit.setToolTip(_translate("DialogConverterEditDictionary", "Изменить выбранное слово и его спряжения\n"
" всловаре для конвертирования."))
        self.tbtn_edit.setText(_translate("DialogConverterEditDictionary", "Изменить\n"
"слово"))
        self.tbtn_delete.setToolTip(_translate("DialogConverterEditDictionary", "Удалить выбраное слово из словаря для конвертирования."))
        self.tbtn_delete.setText(_translate("DialogConverterEditDictionary", "Delete"))
        self.le_filter.setToolTip(_translate("DialogConverterEditDictionary", "Строка поиска словаря по словарю для конвертирования."))
        self.le_filter.setPlaceholderText(_translate("DialogConverterEditDictionary", "введите слово для поиска"))
        self.tbtn_clear_filter.setToolTip(_translate("DialogConverterEditDictionary", "Очистить поле поиска слова по словарю."))
        self.tbtn_clear_filter.setText(_translate("DialogConverterEditDictionary", "Сбросить\n"
"фильтр"))
        self.tw_replacement_dictionary.setToolTip(_translate("DialogConverterEditDictionary", "Поле вывода таблицы со значениями из словаря для заменыслов используемом впрограмме."))
        self.tw_replacement_dictionary.setSortingEnabled(True)
        item = self.tw_replacement_dictionary.horizontalHeaderItem(0)
        item.setText(_translate("DialogConverterEditDictionary", "Первое лицо (ед. число)"))
        item = self.tw_replacement_dictionary.horizontalHeaderItem(1)
        item.setText(_translate("DialogConverterEditDictionary", "Третье лицо (ед. число)"))
        item = self.tw_replacement_dictionary.horizontalHeaderItem(2)
        item.setText(_translate("DialogConverterEditDictionary", "Первое лицо (мн. число)"))
        item = self.tw_replacement_dictionary.horizontalHeaderItem(3)
        item.setText(_translate("DialogConverterEditDictionary", "Третье лицо (мн. число)"))
        item = self.tw_replacement_dictionary.horizontalHeaderItem(4)
        item.setText(_translate("DialogConverterEditDictionary", "Неопределенная форма"))
        self.l_sum_info.setToolTip(_translate("DialogConverterEditDictionary", "Информация о словаре для замены слов."))
        self.l_sum_info.setText(_translate("DialogConverterEditDictionary", "Всего в словаре {} слов для замены."))
import res_rc
