# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\sours\UI\d_setting_app.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogSettingAll(object):
    def setupUi(self, DialogSettingAll):
        DialogSettingAll.setObjectName("DialogSettingAll")
        DialogSettingAll.resize(680, 466)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DialogSettingAll.sizePolicy().hasHeightForWidth())
        DialogSettingAll.setSizePolicy(sizePolicy)
        self.verticalLayout_main = QtWidgets.QVBoxLayout(DialogSettingAll)
        self.verticalLayout_main.setObjectName("verticalLayout_main")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lbl_interface = QtWidgets.QLabel(DialogSettingAll)
        self.lbl_interface.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_interface.setObjectName("lbl_interface")
        self.horizontalLayout_6.addWidget(self.lbl_interface)
        self.cmb_interface = QtWidgets.QComboBox(DialogSettingAll)
        self.cmb_interface.setObjectName("cmb_interface")
        self.cmb_interface.addItem("")
        self.cmb_interface.addItem("")
        self.horizontalLayout_6.addWidget(self.cmb_interface)
        self.verticalLayout_main.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.l_language = QtWidgets.QLabel(DialogSettingAll)
        self.l_language.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.l_language.setObjectName("l_language")
        self.horizontalLayout_5.addWidget(self.l_language)
        self.cmb_language = QtWidgets.QComboBox(DialogSettingAll)
        self.cmb_language.setObjectName("cmb_language")
        self.cmb_language.addItem("")
        self.cmb_language.addItem("")
        self.horizontalLayout_5.addWidget(self.cmb_language)
        self.verticalLayout_main.addLayout(self.horizontalLayout_5)
        self.tabWidget = QtWidgets.QTabWidget(DialogSettingAll)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setIconSize(QtCore.QSize(24, 24))
        self.tabWidget.setObjectName("tabWidget")
        self.verticalLayout_main.addWidget(self.tabWidget)
        self.dbn_box = QtWidgets.QDialogButtonBox(DialogSettingAll)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dbn_box.sizePolicy().hasHeightForWidth())
        self.dbn_box.setSizePolicy(sizePolicy)
        self.dbn_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.dbn_box.setObjectName("dbn_box")
        self.verticalLayout_main.addWidget(self.dbn_box)

        self.retranslateUi(DialogSettingAll)
        self.cmb_language.currentIndexChanged['int'].connect(DialogSettingAll.changeLanguage) # type: ignore
        self.dbn_box.accepted.connect(DialogSettingAll.saveSetting) # type: ignore
        self.dbn_box.rejected.connect(DialogSettingAll.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DialogSettingAll)

    def retranslateUi(self, DialogSettingAll):
        _translate = QtCore.QCoreApplication.translate
        DialogSettingAll.setWindowTitle(_translate("DialogSettingAll", "Setting"))
        self.lbl_interface.setText(_translate("DialogSettingAll", "Interface:"))
        self.cmb_interface.setItemText(0, _translate("DialogSettingAll", "Classic"))
        self.cmb_interface.setItemText(1, _translate("DialogSettingAll", "Modern"))
        self.l_language.setText(_translate("DialogSettingAll", "Interface language:"))
        self.cmb_language.setItemText(0, _translate("DialogSettingAll", "English"))
        self.cmb_language.setItemText(1, _translate("DialogSettingAll", "Русский"))
