# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\sours\UI\d_send_mail.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogSendDevMail(object):
    def setupUi(self, DialogSendDevMail):
        DialogSendDevMail.setObjectName("DialogSendDevMail")
        DialogSendDevMail.setWindowModality(QtCore.Qt.ApplicationModal)
        DialogSendDevMail.resize(592, 378)
        self.verticalLayout = QtWidgets.QVBoxLayout(DialogSendDevMail)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(DialogSendDevMail)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.groupBox = QtWidgets.QGroupBox(DialogSendDevMail)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setContentsMargins(2, 3, 2, 2)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_2.addWidget(self.textEdit)
        self.verticalLayout.addWidget(self.groupBox)
        self.buttonBox = QtWidgets.QDialogButtonBox(DialogSendDevMail)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(DialogSendDevMail)
        self.buttonBox.rejected.connect(DialogSendDevMail.reject) # type: ignore
        self.buttonBox.accepted.connect(DialogSendDevMail.send_mail) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DialogSendDevMail)

    def retranslateUi(self, DialogSendDevMail):
        _translate = QtCore.QCoreApplication.translate
        DialogSendDevMail.setWindowTitle(_translate("DialogSendDevMail", "Письмо для разработчика"))
        self.label.setText(_translate("DialogSendDevMail", "Отредактируйте текст письма и отправьте его на электронную почту- andmoni@yandex.ru\n"
"                        "))
        self.groupBox.setToolTip(_translate("DialogSendDevMail", "Напишите текст письма для меня"))
        self.groupBox.setTitle(_translate("DialogSendDevMail", "Текст письма:"))
        self.textEdit.setHtml(_translate("DialogSendDevMail", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">to: andmoni@yandex.ru</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">e-mail: Добрый день, Андрей! Спасибо за программу.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">В программе «Конвертер показаний» я нашел ошибку.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">[Описание ошибки]</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Я придумал как сделать программу лучше.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">[Описание улучшений]</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Спасибо за Ваш труд.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">С уважением, (ваше имя).</span></p></body></html>"))
