# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\sours\UI\w_converter.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WidgetConverterText(object):
    def setupUi(self, WidgetConverterText):
        WidgetConverterText.setObjectName("WidgetConverterText")
        WidgetConverterText.resize(253, 234)
        self.verticalLayout = QtWidgets.QVBoxLayout(WidgetConverterText)
        self.verticalLayout.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.lbl_status_info = QtWidgets.QLabel(WidgetConverterText)
        self.lbl_status_info.setObjectName("lbl_status_info")
        self.horizontalLayout_2.addWidget(self.lbl_status_info)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.pbtnbox = QtWidgets.QFrame(WidgetConverterText)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbtnbox.sizePolicy().hasHeightForWidth())
        self.pbtnbox.setSizePolicy(sizePolicy)
        self.pbtnbox.setObjectName("pbtnbox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.pbtnbox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(288, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pbtn_men = QtWidgets.QPushButton(self.pbtnbox)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ico/icons/men0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbtn_men.setIcon(icon)
        self.pbtn_men.setIconSize(QtCore.QSize(24, 24))
        self.pbtn_men.setObjectName("pbtn_men")
        self.horizontalLayout.addWidget(self.pbtn_men)
        self.pbtn_women = QtWidgets.QPushButton(self.pbtnbox)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/ico/icons/women0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbtn_women.setIcon(icon1)
        self.pbtn_women.setIconSize(QtCore.QSize(24, 24))
        self.pbtn_women.setObjectName("pbtn_women")
        self.horizontalLayout.addWidget(self.pbtn_women)
        spacerItem2 = QtWidgets.QSpacerItem(287, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addWidget(self.pbtnbox)

        self.retranslateUi(WidgetConverterText)
        self.pbtn_men.clicked.connect(WidgetConverterText.magic) # type: ignore
        self.pbtn_women.clicked.connect(WidgetConverterText.magic) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(WidgetConverterText)

    def retranslateUi(self, WidgetConverterText):
        _translate = QtCore.QCoreApplication.translate
        WidgetConverterText.setWindowTitle(_translate("WidgetConverterText", "Converter"))
        self.lbl_status_info.setText(_translate("WidgetConverterText", "TextLabel"))
        self.pbtn_men.setText(_translate("WidgetConverterText", "Men"))
        self.pbtn_women.setText(_translate("WidgetConverterText", "Women"))
import res_rc
